---
title: "MBASED_F1_Results"
output: html_document
---

```{r setup, include=FALSE}
library(MBASED)
library(tidyverse)
library(magrittr)
```

Helper Functions for summarizing results and getting significant ones
```{r Analyzing Results Functions}
SummarizeASEResults_2s <- function(MBASEDOutput) {
  # Output: geneOutputDF is an easier way to look at MAF and p-values at the same time
  geneOutputDF <- data.frame(
    majorAlleleFrequencyDifference=assays(MBASEDOutput)$majorAlleleFrequencyDifference[,1],
    pValueASE=assays(MBASEDOutput)$pValueASE[,1],
    pValueHeterogeneity=assays(MBASEDOutput)$pValueHeterogeneity[,1]
  )
  
  lociOutputGR <- rowRanges(metadata(MBASEDOutput)$locusSpecificResults)
  lociOutputGR$allele1IsMajor <- assays(metadata(MBASEDOutput)$locusSpecificResults)$allele1IsMajor[,1]

  lociOutputGR$MAFDifference <- assays(metadata(MBASEDOutput)$locusSpecificResults)$MAFDifference[,1]
  lociOutputList <- split(lociOutputGR, factor(lociOutputGR$aseID, levels=unique(lociOutputGR$aseID)))
  return(list(geneOutput=geneOutputDF, locusOutput=lociOutputList))
}

SummarizeASEResults_1s <- function(MBASEDOutput) {
  # Same as above, but for single sample results
  geneOutputDF <- data.frame(
    majorAlleleFrequency = assays(MBASEDOutput)$majorAlleleFrequency[,1],
    pValueASE=assays(MBASEDOutput)$pValueASE[,1],
    pValueHeterogeneity=assays(MBASEDOutput)$pValueHeterogeneity[,1]
  )
  
  lociOutputGR <- rowRanges(metadata(MBASEDOutput)$locusSpecificResults)
  lociOutputGR$allele1IsMajor <- assays(metadata(MBASEDOutput)$locusSpecificResults)$allele1IsMajor[,1]

  lociOutputGR$MAF <- assays(metadata(MBASEDOutput)$locusSpecificResults)$MAF[,1]
  lociOutputList <- split(lociOutputGR, factor(lociOutputGR$aseID, levels=unique(lociOutputGR$aseID)))
  return(list(geneOutput=geneOutputDF, locusOutput=lociOutputList))
}

ExtractASE <- function(MBASEDSummary, samples = 1, p = 0.05, MAFD = 0.2, heterogeneity = FALSE) {
  # Extract only desired genes
  # p = p-value cutoff, MAFD = major allele frequency difference cutoff,
  # Modify p and MAFD to vary the strictness of selection.

  # Apply Benjamini-Hochberg (fdr) correction for multiple testing
  if(heterogeneity == TRUE) {
    MBASEDSummary$geneOutput %<>% mutate(pValueHeterogeneity = ifelse(is.na(pValueHeterogeneity),
                                                                      1, pValueHeterogeneity))
    adjustedP <- p.adjust(MBASEDSummary$geneOutput$pValueHeterogeneity, method = "BH",
                          n = length(MBASEDSummary$geneOutput$pValueASE))
    MBASEDSummary$geneOutput$pValueHeterogeneity <- adjustedP
  } else {
    adjustedP <- p.adjust(MBASEDSummary$geneOutput$pValueASE, method = "BH", 
                          n = length(MBASEDSummary$geneOutput$pValueASE))
    MBASEDSummary$geneOutput$pValueASE <-  adjustedP
  }
  
  if(samples == 2) {
  ASEindexes <- adjustedP < p & 
    abs(MBASEDSummary$geneOutput$majorAlleleFrequencyDifference) > MAFD
  } else {
    ASEindexes <- adjustedP < p & 
    (abs(MBASEDSummary$geneOutput$majorAlleleFrequency) > 0.5 + MAFD |
    abs(MBASEDSummary$geneOutput$majorAlleleFrequency) < 0.5 - MAFD)
  }
  
  significantResults <- list(geneOutput = MBASEDSummary$geneOutput[ASEindexes, ], 
                             locusOutput = MBASEDSummary$locusOutput[ASEindexes, ])
  return(significantResults)
}
```

Combine all the MBASED results into one file, since we subsetted the data earlier to run it in parallel.  
This chunk does not need to be run again.  
```{r Combine all the files into one, include = FALSE}
rm(list=ls())

# filenames <- list.files("Results_Beta/414vs415", pattern="*.Rdata", full.names=TRUE)
filenames <- list.files("Results_Beta/415vs414", pattern="*.Rdata", full.names=TRUE)
# filenames <- list.files("Results_Binom/414vs415", pattern="*.Rdata", full.names=TRUE)
# filenames <- list.files("Results_Binom/415vs414", pattern="*.Rdata", full.names=TRUE)

for(i in 1:length(filenames)) {
  load(filenames[i])
}

rm(i)
rm(filenames)
datanames <- ls()

final <- do.call(rbind, mget(datanames))

compiledMetadata <- metadata(final)[[1]]
for(i in 2:length(metadata(final))) {
  compiledMetadata <- rbind(compiledMetadata, metadata(final)[[i]])
}

metadata(final) <- list(locusSpecificResults= compiledMetadata)

# final414vs415b <- final
final415vs414b <- final
# final414vs415 <- final
# final415vs414 <- final

# save(final414vs415b, file = "Results_Beta/final414vs415b.Rdata")
save(final415vs414b, file = "Results_Beta/final415vs414b.Rdata")
# save(final414vs415, file = "Results_Binom/final414vs415.Rdata")
# save(final415vs414, file = "Results_Binom/final415vs414.Rdata")
```

## Analysis

Loading my results
```{r Analysis and summary}
load("~/repos/KIAT_F1/MBASED/Results_Beta/final414vs415b.Rdata")
load("~/repos/KIAT_F1/MBASED/Results_Beta/final415vs414b.Rdata") 
load("~/repos/KIAT_F1/MBASED/Results_Binom/final414vs415.Rdata") 
load("~/repos/KIAT_F1/MBASED/Results_Binom/final415vs414.Rdata") 

# class(results$geneOutput) # data.frame containing: GeneID, MAF Difference, p-value, and p-value for heterogenous slicing
# class(results$locusOutput) # GRangesList containing all SNVs, organized by gene

significant <- final414vs415 %>% SummarizeASEResults_2s() %>% ExtractASE(samples = 2)
significantRev <- final415vs414 %>% SummarizeASEResults_2s() %>% ExtractASE(samples = 2)
significantb <- final414vs415b %>% SummarizeASEResults_2s() %>% ExtractASE(samples = 2)
significantRevb <- final415vs414b %>% SummarizeASEResults_2s() %>% ExtractASE(samples = 2)

save(significantb, file = "Results_Beta/significantb.Rdata")

dim(significant$geneOutput) # 607 genes found in ASE using F1 414 as sample 1 and a binomial model
dim(significantRev$geneOutput) # 603 genes
dim(significantb$geneOutput) #88 genes found in ASE using F1 414 as sample 1
dim(significantRevb$geneOutput) #94 genes found in ASE using F1 415 as sample 2

genes <- rownames(significant$geneOutput) # Names of the genes 
genesRev <- rownames(significantRev$geneOutput) 
genesb <- rownames(significantb$geneOutput)
genesRevb <- rownames(significantRevb$geneOutput)

matches <- intersect(genesb, genesRevb) # 86 genes in agreement
differences414 <- setdiff(genesb, genesRevb) # 2 genes unique when 414 is the first sample
differences415 <- setdiff(genesRevb, genesb) # 8 genes unique when 415 is the first sample

aseGenesBinom <- union(genes, genesRev) # All the genes 
aseGenesBeta <- union(genesb, genesRevb) # All the genes 
matchesBetweenBetaAndBinomial <- intersect(total, totalb)

save(aseGenesBeta, file = "aseGenesBeta.Rdata")
save(aseGenesBinom, file = "aseGenesBinom.Rdata")
```

### One Sample Analysis
```{r}
load("~/repos/KIAT_F1/MBASED/Results_F1414/BETA.MBASED.F1.414.Rdata")

significant <- BETA.MBASED.F1.414 %>% SummarizeASEResults_1s() %>% ExtractASE()
dim(significant$geneOutput)
aseGenes414 <- rownames(significant$geneOutput)

save(aseGenes414, file = "aseGenes414.Rdata")
```

Distribution of p-values for heterogeneity
```{r}
summaryASE <- BETA.MBASED.F1.414 %>% SummarizeASEResults_1s()

p.adjust(summaryASE$geneOutput$pValueHeterogeneity) %>% reshape2::melt() %>% filter(value < 1) %>%
  ggplot() + geom_histogram(aes(x = value))

significant <- summaryASE %>% ExtractASE(heterogeneity = TRUE)
```
Only 3 genes showed both ASE and heterogeneity. 